//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace Dashboard2017.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("149")]
        public uint lowerHue {
            get {
                return ((uint)(this["lowerHue"]));
            }
            set {
                this["lowerHue"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("255")]
        public uint upperHue {
            get {
                return ((uint)(this["upperHue"]));
            }
            set {
                this["upperHue"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("230")]
        public uint lowerSaturation {
            get {
                return ((uint)(this["lowerSaturation"]));
            }
            set {
                this["lowerSaturation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("255")]
        public uint upperSaturation {
            get {
                return ((uint)(this["upperSaturation"]));
            }
            set {
                this["upperSaturation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public uint lowerBrightness {
            get {
                return ((uint)(this["lowerBrightness"]));
            }
            set {
                this["lowerBrightness"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("218")]
        public uint upperBrightness {
            get {
                return ((uint)(this["upperBrightness"]));
            }
            set {
                this["upperBrightness"] = value;
            }
        }
    }
}
